# TRMNLP configuration
# {{ env.VARIABLE }} interpolation is available here
---
# auto-reload when files change (`watch: false` to disable)
watch:
  - .trmnlp.yml
  - src

# values of custom fields (defined in src/settings.yml)
custom_fields: {
  # up to 5 metrics - "today", "yesterday", "this_week", "this_month", "last_3_months", "last_year", "last_7_days", "last_30_days", "last_90_days", "last_year"

  # 5 metrics
  # dashboard_metrics: [
  #     "today",
  #     "yesterday",
  #     "this_week",
  #     "last_week",
  #     "last_7_days"
  #   ],

  # 7 metrics
  # dashboard_metrics: [
  #     "today",
  #     "yesterday",
  #     "this_week",
  #     "last_week",
  #     "last_7_days",
  #     "last_30_days",
  #     "this_month"
  #   ],



  # 10 metrics
  dashboard_metrics: [
      "today",
      "yesterday",
      "this_week",
      "last_week",
      "last_7_days",
      "last_30_days",
      "this_month",
      "last_month",
      "last_3_months",
      "last_year"
    ],
  layout: "contributions",  # "line", "bars", "contributions"
  # layout: "line",  # "true", "bars", "contributions"
  # layout: "bars",  # "line", "bars", "contributions"
  layout_half_horizontal: "line",  # "line", "bars", "contributions"
  # layout_half_horizontal: "contributions",  # "line", "bars", "contributions"
  # "last_7_days", "last_30_days", "last_90_days", "last_year", "all_time"
  # timeframe: "last_7_days",  
  # timeframe: "last_30_days",
  timeframe: "last_90_days",  
  # timeframe: "last_year",
  # enable_grouping: true,  # "true" or "false"
  enable_grouping: false,  # "true" or "false"
  show_x_axis_labels: 'false',
  show_y_axis_labels: 'false',
  contributions_period: "current_year", 
  # date format for x-axis labels, options: "%d.%m", "%d/%m", "%m-%d", "%d %b", "%b %d", "%a", "%Y-%m-%d"
  # date_format: "%d.%m",  
  # date_format: "%d/%m",
  # date_format: "%m-%d",
  # date_format: "%d %b",
  # date_format: "%b %d",
  # date_format: "%a",
  # date_format: "%Y-%m-%d",
  date_format: "%d.%m.%Y",
  show_title_bar: true,  # "true" or "false"
  show_contributions_legend: 'false',  # "true" or "false"
}

# override variables
variables:
  trmnl:
    plugin_settings:
      #last year
      polling_url: https://wakatime.com/share/@flrnz/3526e3f7-063a-4cc3-911e-d297f569335d.json
      # all time
      # polling_url: https://wakatime.com/share/@flrnz/e6f1249d-8dcd-457a-af76-a30b4131af33.json
      