# TRMNLP configuration
# {{ env.VARIABLE }} interpolation is available here
---
# auto-reload when files change (`watch: false` to disable)
watch:
  - .trmnlp.yml
  - src

# values of custom fields (defined in src/settings.yml)
custom_fields: {
  # up to 5 metrics - "today", "yesterday", "this_week", "this_month", "last_3_months", "last_year", "last_7_days", "last_30_days", "last_90_days", "last_year"
  # dashboard_metrics: "today,this_week,this_month,last_3_months,last_year", today 
  # dashboard_metrics: "last_3_months,last_year",
  # dashboard_metrics: "last_7_days,last_30_days,last_90_days,last_year",
  dashboard_metrics: "today,yesterday,this_week,last_week,last_7_days,this_month,last_month,last_30_days,last_3_months,last_year",  
  # layout: "contributions",  # "line", "bars", "contributions"
  layout: "line",  # "true", "bars", "contributions"
  # layout: "bars",  # "line", "bars", "contributions"
  # timeframe: "last_7_days",  # "last_7_days", "last_30_days", "last_90_days", "last_year", "all_time"
  timeframe: "last_30_days",
  # timeframe: "last_90_days",  
  # timeframe: "last_year",
  enable_grouping: true,  # "true" or "false"
  # enable_grouping: false,  # "true" or "false"
  # contributions_period: "last_365_days"  # "current_year", "last_365_days"
  contributions_period: "current_year", 
  # date format for x-axis labels, options: "%d.%m", "%d/%m", "%m-%d", "%d %b", "%b %d", "%a", "%Y-%m-%d"
  # date_format: "%d.%m",  
  # date_format: "%d/%m",
  # date_format: "%m-%d",
  # date_format: "%d %b",
  # date_format: "%b %d",
  # date_format: "%a",
  # date_format: "%Y-%m-%d",
  date_format: "%d.%m.%Y",
  # show_title_bar: false,  # "true" or "false"
}

# override variables
variables:
  trmnl:
    plugin_settings:
      #last year
      polling_url: https://wakatime.com/share/@flrnz/3526e3f7-063a-4cc3-911e-d297f569335d.json
      # all time
      # polling_url: https://wakatime.com/share/@flrnz/e6f1249d-8dcd-457a-af76-a30b4131af33.json
      